# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      displayName: Build Quarkus application
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        options: '-DskipTests'
        jdkVersionOption: '1.21'
    - script: |
        docker build -f src/main/docker/Dockerfile.jvm -t api:$(tag) .
      displayName: Build Docker image
      workingDirectory: '$(Build.SourcesDirectory)'
