quarkus.http.cors.enabled=true

quarkus.http.cors.origins=/.*/
%dev.quarkus.http.cors.origins=/.*/


# Allowed HTTP methods
#quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Allowed headers
#quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

quarkus.hibernate-orm.log.sql=false

%dev.quarkus.datasource.dev-ui.allow-sql=true
%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true


#%prod.quarkus.datasource.db-kind=postgresql
#%prod.quarkus.datasource.username=postgres@postgresqlserver-fsi
#%prod.quarkus.datasource.password=C0mplexP@ssw0rd
#%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/fsi

%prod.quarkus.datasource.username=${USERNAME:postgres@postgresqlserver-nextgen}
%prod.quarkus.datasource.password=${PASSWORD:C0mplexP@ssw0rd}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRESQL:postgresql}:5432/nextgen


%prod.quarkus.datasource.jdbc.pooling-enabled=true
%prod.quarkus.log.category."io.agroal.pool".level=DEBUG
%prod.quarkus.datasource.jdbc.min-size=1
%prod.quarkus.datasource.jdbc.max-size=2
  # check every 1 minutes
%prod.quarkus.datasource.jdbc.idle-removal-interval=1
# max lifetime for a connection
%prod.quarkus.datasource.jdbc.max-connection-lifetime=2
# warn after 2 minutes of idle
%prod.quarkus.datasource.jdbc.leak-detection-interval=2

# production, init containers will pre-load the data
%prod.quarkus.hibernate-orm.database.generation=update
