quarkus.http.cors.enabled=true

quarkus.http.cors.origins=/.*/
%dev.quarkus.http.cors.origins=/.*/


# Allowed HTTP methods
#quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Allowed headers
#quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with


%dev.quarkus.datasource.dev-ui.allow-sql=true

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
